name: GitHub Packages Build Pipeline

on:
  workflow_dispatch:
    inputs:
      project:
        description: Project to deploy
        required: true
        type: choice
        options:
          - kotlin-utility


permissions:
  contents: read
  packages: write

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    defaults:
      run:
        shell: bash
        working-directory: ./${{ inputs.project }}

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set up JDK
        uses: actions/setup-java@main
        with:
          java-version: 21
          distribution: temurin

      - name: Maven Cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Maven Build
        run: mvn clean deploy -s ../.m2/settings.xml -fae